// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: account_delete.proto

package protomsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDeleteRequest) Reset() {
	*x = AccountDeleteRequest{}
	mi := &file_account_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeleteRequest) ProtoMessage() {}

func (x *AccountDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeleteRequest.ProtoReflect.Descriptor instead.
func (*AccountDeleteRequest) Descriptor() ([]byte, []int) {
	return file_account_delete_proto_rawDescGZIP(), []int{0}
}

func (x *AccountDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountDeleteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDeleteResponse) Reset() {
	*x = AccountDeleteResponse{}
	mi := &file_account_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeleteResponse) ProtoMessage() {}

func (x *AccountDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeleteResponse.ProtoReflect.Descriptor instead.
func (*AccountDeleteResponse) Descriptor() ([]byte, []int) {
	return file_account_delete_proto_rawDescGZIP(), []int{1}
}

func (x *AccountDeleteResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AccountDeleteCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountDeleteCancelRequest) Reset() {
	*x = AccountDeleteCancelRequest{}
	mi := &file_account_delete_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountDeleteCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDeleteCancelRequest) ProtoMessage() {}

func (x *AccountDeleteCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_delete_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDeleteCancelRequest.ProtoReflect.Descriptor instead.
func (*AccountDeleteCancelRequest) Descriptor() ([]byte, []int) {
	return file_account_delete_proto_rawDescGZIP(), []int{2}
}

func (x *AccountDeleteCancelRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AccountDeleteCancelRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_account_delete_proto protoreflect.FileDescriptor

const file_account_delete_proto_rawDesc = "" +
	"\n" +
	"\x14account_delete.proto\x12\x06ppgram\"N\n" +
	"\x14AccountDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"5\n" +
	"\x15AccountDeleteResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"T\n" +
	"\x1aAccountDeleteCancelRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpasswordB>Z*github.com/ppgram/server/protomsg;protomsg\xaa\x02\x0fPPgram.Protobufb\x06proto3"

var (
	file_account_delete_proto_rawDescOnce sync.Once
	file_account_delete_proto_rawDescData []byte
)

func file_account_delete_proto_rawDescGZIP() []byte {
	file_account_delete_proto_rawDescOnce.Do(func() {
		file_account_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_delete_proto_rawDesc), len(file_account_delete_proto_rawDesc)))
	})
	return file_account_delete_proto_rawDescData
}

var file_account_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_delete_proto_goTypes = []any{
	(*AccountDeleteRequest)(nil),       // 0: ppgram.AccountDeleteRequest
	(*AccountDeleteResponse)(nil),      // 1: ppgram.AccountDeleteResponse
	(*AccountDeleteCancelRequest)(nil), // 2: ppgram.AccountDeleteCancelRequest
}
var file_account_delete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_delete_proto_init() }
func file_account_delete_proto_init() {
	if File_account_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_delete_proto_rawDesc), len(file_account_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_delete_proto_goTypes,
		DependencyIndexes: file_account_delete_proto_depIdxs,
		MessageInfos:      file_account_delete_proto_msgTypes,
	}.Build()
	File_account_delete_proto = out.File
	file_account_delete_proto_goTypes = nil
	file_account_delete_proto_depIdxs = nil
}
