// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: update.proto

package protomsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdateRequest) Reset() {
	*x = ClientUpdateRequest{}
	mi := &file_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdateRequest) ProtoMessage() {}

func (x *ClientUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdateRequest.ProtoReflect.Descriptor instead.
func (*ClientUpdateRequest) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{0}
}

type ClientUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdateResponse) Reset() {
	*x = ClientUpdateResponse{}
	mi := &file_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdateResponse) ProtoMessage() {}

func (x *ClientUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdateResponse.ProtoReflect.Descriptor instead.
func (*ClientUpdateResponse) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{1}
}

type ServerUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdateRequest) Reset() {
	*x = ServerUpdateRequest{}
	mi := &file_update_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdateRequest) ProtoMessage() {}

func (x *ServerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdateRequest.ProtoReflect.Descriptor instead.
func (*ServerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{2}
}

type ServerUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdateResponse) Reset() {
	*x = ServerUpdateResponse{}
	mi := &file_update_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdateResponse) ProtoMessage() {}

func (x *ServerUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdateResponse.ProtoReflect.Descriptor instead.
func (*ServerUpdateResponse) Descriptor() ([]byte, []int) {
	return file_update_proto_rawDescGZIP(), []int{3}
}

var File_update_proto protoreflect.FileDescriptor

const file_update_proto_rawDesc = "" +
	"\n" +
	"\fupdate.proto\x12\x06ppgram\"\x15\n" +
	"\x13ClientUpdateRequest\"\x16\n" +
	"\x14ClientUpdateResponse\"\x15\n" +
	"\x13ServerUpdateRequest\"\x16\n" +
	"\x14ServerUpdateResponseB>Z*github.com/ppgram/server/protomsg;protomsg\xaa\x02\x0fPPgram.Protobufb\x06proto3"

var (
	file_update_proto_rawDescOnce sync.Once
	file_update_proto_rawDescData []byte
)

func file_update_proto_rawDescGZIP() []byte {
	file_update_proto_rawDescOnce.Do(func() {
		file_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_proto_rawDesc), len(file_update_proto_rawDesc)))
	})
	return file_update_proto_rawDescData
}

var file_update_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_update_proto_goTypes = []any{
	(*ClientUpdateRequest)(nil),  // 0: ppgram.ClientUpdateRequest
	(*ClientUpdateResponse)(nil), // 1: ppgram.ClientUpdateResponse
	(*ServerUpdateRequest)(nil),  // 2: ppgram.ServerUpdateRequest
	(*ServerUpdateResponse)(nil), // 3: ppgram.ServerUpdateResponse
}
var file_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_proto_init() }
func file_update_proto_init() {
	if File_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_proto_rawDesc), len(file_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_proto_goTypes,
		DependencyIndexes: file_update_proto_depIdxs,
		MessageInfos:      file_update_proto_msgTypes,
	}.Build()
	File_update_proto = out.File
	file_update_proto_goTypes = nil
	file_update_proto_depIdxs = nil
}
